/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.emptyBreadcrumbs[_ngcontent-%COMP%]{\r\n  height: 100%;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvZ2V0dGkvUHJvZ2V0dGlBbmd1bGFyL2NvbnRleHQvc3JjL3RlbXBsYXRlcy9uYXZiYXIvbmF2YmFyLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1Byb2dldHRpL1Byb2dldHRpQW5ndWxhci9jb250ZXh0L3NyYy90ZW1wbGF0ZXMvbmF2YmFyL25hdmJhci5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
